// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystem_V1.Data;

#nullable disable

namespace SchoolManagementSystem_V1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230519161216_initail")]
    partial class initail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Admin", b =>
                {
                    b.Property<long>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdminId"), 1L, 1);

                    b.Property<bool?>("ClassRoutineManagement")
                        .HasColumnType("bit");

                    b.Property<bool?>("ExamManagement")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PaymentManagement")
                        .HasColumnType("bit");

                    b.Property<bool?>("ResultManagement")
                        .HasColumnType("bit");

                    b.Property<bool?>("StudentManagement")
                        .HasColumnType("bit");

                    b.Property<bool?>("StuffManagement")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubjectManagement")
                        .HasColumnType("bit");

                    b.Property<bool?>("TeacherManagement")
                        .HasColumnType("bit");

                    b.Property<long?>("Teacherid")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.HasIndex("Teacherid");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Branch", b =>
                {
                    b.Property<long>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BranchId"), 1L, 1);

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Building", b =>
                {
                    b.Property<long>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BuildingId"), 1L, 1);

                    b.Property<string>("BuildingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CampusId")
                        .HasColumnType("bigint");

                    b.HasKey("BuildingId");

                    b.HasIndex("CampusId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Campus", b =>
                {
                    b.Property<long>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CampusId"), 1L, 1);

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("CampusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ShiftId")
                        .HasColumnType("bigint");

                    b.HasKey("CampusId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Campuses");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Class", b =>
                {
                    b.Property<long>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClassId"), 1L, 1);

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CurriculumId")
                        .HasColumnType("bigint");

                    b.HasKey("ClassId");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.ClassRoutine", b =>
                {
                    b.Property<long>("ClassRoutineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClassRoutineId"), 1L, 1);

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SectionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Shiftid")
                        .HasColumnType("bigint");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeekDay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassRoutineId");

                    b.HasIndex("ClassId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SectionId");

                    b.HasIndex("Shiftid");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassRoutines");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Curriculum", b =>
                {
                    b.Property<long>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CurriculumId"), 1L, 1);

                    b.Property<long?>("CampusId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurriculumName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurriculumId");

                    b.HasIndex("CampusId");

                    b.ToTable("Curricula");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Designation", b =>
                {
                    b.Property<long>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DesignationId"), 1L, 1);

                    b.Property<string>("DesignationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignationId");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecordCreatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Exam", b =>
                {
                    b.Property<long>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExamId"), 1L, 1);

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PassingMarks")
                        .HasColumnType("int");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TotalMarks")
                        .HasColumnType("int");

                    b.HasKey("ExamId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.GradingSystem", b =>
                {
                    b.Property<long>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GradeId"), 1L, 1);

                    b.Property<long?>("Classid")
                        .HasColumnType("bigint");

                    b.Property<string>("GradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxMarks")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumMarks")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("Classid");

                    b.ToTable("GradingSystems");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GroupId"), 1L, 1);

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Room", b =>
                {
                    b.Property<long>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoomId"), 1L, 1);

                    b.Property<long?>("BuildingId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Section", b =>
                {
                    b.Property<long>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SectionId"), 1L, 1);

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Session", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionId"), 1L, 1);

                    b.Property<string>("SessionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Shift", b =>
                {
                    b.Property<long>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShiftId"), 1L, 1);

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentId"), 1L, 1);

                    b.Property<DateTime?>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CampusId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherNid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherNid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SectionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShiftId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentId");

                    b.HasIndex("CampusId");

                    b.HasIndex("ClassId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SessionId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentClassRoutine", b =>
                {
                    b.Property<long>("StudentClassRoutineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentClassRoutineId"), 1L, 1);

                    b.Property<long?>("ClassRoutineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentClassRoutineId");

                    b.HasIndex("ClassRoutineId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentClassRoutines");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentExamRoutine", b =>
                {
                    b.Property<long>("StudentExamRoutineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentExamRoutineId"), 1L, 1);

                    b.Property<long?>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentExamRoutineId");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentExamRoutines");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentPayment", b =>
                {
                    b.Property<long>("StudentPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentPaymentId"), 1L, 1);

                    b.Property<decimal?>("PaymentAmmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentPaymentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentPayments");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentPortal", b =>
                {
                    b.Property<long>("StudentPortalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentPortalId"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentPortalId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentPortals");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentPromotion", b =>
                {
                    b.Property<long>("StudentPromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentPromotionId"), 1L, 1);

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<string>("PromotionApprover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PromotionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PromotionStatus")
                        .HasColumnType("bit");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentPromotionId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentPromotions");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentResult", b =>
                {
                    b.Property<long>("StudentResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentResultId"), 1L, 1);

                    b.Property<long?>("GradeId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ObtainedMark")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentResultId");

                    b.HasIndex("GradeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentResults");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentSubject", b =>
                {
                    b.Property<long>("StudentSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentSubjectId"), 1L, 1);

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentSubjectId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Stuff", b =>
                {
                    b.Property<long>("StuffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StuffId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StuffId");

                    b.ToTable("Stuffs");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Subject", b =>
                {
                    b.Property<long>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubjectId"), 1L, 1);

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.HasIndex("ClassId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.SuperAdmin", b =>
                {
                    b.Property<long>("SuperAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SuperAdminId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuperAdminId");

                    b.ToTable("SuperAdmins");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Teacher", b =>
                {
                    b.Property<long>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherId"), 1L, 1);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherClassRoutine", b =>
                {
                    b.Property<long>("TeacherClassRoutineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherClassRoutineId"), 1L, 1);

                    b.Property<long?>("ClassRoutineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("TeacherClassRoutineId");

                    b.HasIndex("ClassRoutineId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherClassRoutines");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherDesignation", b =>
                {
                    b.Property<long>("TeacherDesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherDesignationId"), 1L, 1);

                    b.Property<long?>("DesignationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("TeacherDesignationId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherDesignations");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherExamRoutine", b =>
                {
                    b.Property<long>("TeacherExamRoutineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherExamRoutineId"), 1L, 1);

                    b.Property<long?>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("TeacherExamRoutineId");

                    b.HasIndex("ExamId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherExamRoutines");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherPortal", b =>
                {
                    b.Property<long>("TeacherPortalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherPortalId"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherPortalId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherPortals");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherSubject", b =>
                {
                    b.Property<long>("TeacherSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherSubjectId"), 1L, 1);

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("TeacherSubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Admin", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Teacher", "Teacher")
                        .WithMany("Admins")
                        .HasForeignKey("Teacherid");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Building", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Campus", "Campus")
                        .WithMany("Buildings")
                        .HasForeignKey("CampusId");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Campus", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Branch", "Branch")
                        .WithMany("Campuses")
                        .HasForeignKey("BranchId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Shift", "Shift")
                        .WithMany("Campuses")
                        .HasForeignKey("ShiftId");

                    b.Navigation("Branch");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Class", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Curriculum", "Curriculum")
                        .WithMany("Classes")
                        .HasForeignKey("CurriculumId");

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.ClassRoutine", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Class", "Class")
                        .WithMany("ClassRoutines")
                        .HasForeignKey("ClassId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Room", "Room")
                        .WithMany("ClassRoutines")
                        .HasForeignKey("RoomId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Section", "Section")
                        .WithMany("ClassRoutines")
                        .HasForeignKey("SectionId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Shift", "Shift")
                        .WithMany("ClassRoutines")
                        .HasForeignKey("Shiftid");

                    b.HasOne("SchoolManagementSystem_V1.Models.Subject", "Subject")
                        .WithMany("ClassRoutines")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Class");

                    b.Navigation("Room");

                    b.Navigation("Section");

                    b.Navigation("Shift");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Curriculum", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Campus", "Campus")
                        .WithMany("Curricula")
                        .HasForeignKey("CampusId");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Exam", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.GradingSystem", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Class", "Class")
                        .WithMany("GradingSystems")
                        .HasForeignKey("Classid");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Room", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Student", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Campus", "Campus")
                        .WithMany("Students")
                        .HasForeignKey("CampusId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Section", "Section")
                        .WithMany("Students")
                        .HasForeignKey("SectionId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Session", "Session")
                        .WithMany("Students")
                        .HasForeignKey("SessionId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Shift", "Shift")
                        .WithMany("Students")
                        .HasForeignKey("ShiftId");

                    b.Navigation("Campus");

                    b.Navigation("Class");

                    b.Navigation("Group");

                    b.Navigation("Section");

                    b.Navigation("Session");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentClassRoutine", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.ClassRoutine", "ClassRoutine")
                        .WithMany("StudentClassRoutines")
                        .HasForeignKey("ClassRoutineId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Student", "Student")
                        .WithMany("StudentClassRoutines")
                        .HasForeignKey("StudentId");

                    b.Navigation("ClassRoutine");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentExamRoutine", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Exam", "Exam")
                        .WithMany("StudentExamRoutines")
                        .HasForeignKey("ExamId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Student", "Student")
                        .WithMany("StudentExamRoutines")
                        .HasForeignKey("StudentId");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentPayment", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Student", "Student")
                        .WithMany("StudentPayments")
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentPortal", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Student", "Student")
                        .WithMany("StudentPortals")
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentPromotion", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Class", "Class")
                        .WithMany("StudentPromotions")
                        .HasForeignKey("ClassId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Student", "Student")
                        .WithMany("StudentPromotions")
                        .HasForeignKey("StudentId");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentResult", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.GradingSystem", "Grade")
                        .WithMany("StudentResults")
                        .HasForeignKey("GradeId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Student", "Student")
                        .WithMany("StudentResults")
                        .HasForeignKey("StudentId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Subject", "Subject")
                        .WithMany("StudentResults")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Grade");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.StudentSubject", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Subject", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Class", "Class")
                        .WithMany("Subjects")
                        .HasForeignKey("ClassId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherClassRoutine", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.ClassRoutine", "ClassRoutine")
                        .WithMany("TeacherClassRoutines")
                        .HasForeignKey("ClassRoutineId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Teacher", "Teacher")
                        .WithMany("TeacherClassRoutines")
                        .HasForeignKey("TeacherId");

                    b.Navigation("ClassRoutine");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherDesignation", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Designation", "Designation")
                        .WithMany("TeacherDesignations")
                        .HasForeignKey("DesignationId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Teacher", "Teacher")
                        .WithMany("TeacherDesignations")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Designation");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherExamRoutine", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Exam", "Exam")
                        .WithMany("TeacherExamRoutines")
                        .HasForeignKey("ExamId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Teacher", "Teacher")
                        .WithMany("TeacherExamRoutines")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Exam");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherPortal", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Teacher", "Teacher")
                        .WithMany("TeacherPortals")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.TeacherSubject", b =>
                {
                    b.HasOne("SchoolManagementSystem_V1.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId");

                    b.HasOne("SchoolManagementSystem_V1.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Branch", b =>
                {
                    b.Navigation("Campuses");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Campus", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Curricula");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Class", b =>
                {
                    b.Navigation("ClassRoutines");

                    b.Navigation("GradingSystems");

                    b.Navigation("StudentPromotions");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.ClassRoutine", b =>
                {
                    b.Navigation("StudentClassRoutines");

                    b.Navigation("TeacherClassRoutines");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Curriculum", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Designation", b =>
                {
                    b.Navigation("TeacherDesignations");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Exam", b =>
                {
                    b.Navigation("StudentExamRoutines");

                    b.Navigation("TeacherExamRoutines");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.GradingSystem", b =>
                {
                    b.Navigation("StudentResults");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Room", b =>
                {
                    b.Navigation("ClassRoutines");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Section", b =>
                {
                    b.Navigation("ClassRoutines");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Session", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Shift", b =>
                {
                    b.Navigation("Campuses");

                    b.Navigation("ClassRoutines");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Student", b =>
                {
                    b.Navigation("StudentClassRoutines");

                    b.Navigation("StudentExamRoutines");

                    b.Navigation("StudentPayments");

                    b.Navigation("StudentPortals");

                    b.Navigation("StudentPromotions");

                    b.Navigation("StudentResults");

                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Subject", b =>
                {
                    b.Navigation("ClassRoutines");

                    b.Navigation("Exams");

                    b.Navigation("StudentResults");

                    b.Navigation("StudentSubjects");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SchoolManagementSystem_V1.Models.Teacher", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("TeacherClassRoutines");

                    b.Navigation("TeacherDesignations");

                    b.Navigation("TeacherExamRoutines");

                    b.Navigation("TeacherPortals");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
